-- =====================================================================
-- BLOQUEAR A QUIEN SE PASE DE SUS HORAS   02-10-2026
-- Recortado el 06-10-2026. Lee la nota de abajo antes de tocarlo.
--
-- QUE HACE. Agrega el interruptor del local: si esta encendido, quien toma un
-- turno abierto y con eso se pasaria de sus horas de contrato recibe un «no»
-- con el motivo, en vez de tomarlo igual.
-- =====================================================================

alter table locales add column if not exists bloquear_sobre_tope boolean not null default false;

-- =====================================================================
-- LO QUE SE QUITO DE AQUI, Y POR QUE
--
-- Este archivo traia ademas una version de `tomar_turno()` del 02-10 que leia
-- la tabla `turnos_abiertos`. El 03-10, `arreglo-sin-asignar.sql` mudo los
-- turnos sin dueño a `asignaciones` y reescribio `tomar_turno()` entero: la
-- version nueva ya consulta `bloquear_sobre_tope`, y ademas sabe de turnos
-- OFRECIDOS, rechaza tomar algo que se pisa con un turno propio («se_pisa») y
-- el «ya_es_tuyo».
--
-- Es decir: pegar hoy la version vieja NO agregaba nada y RETROCEDIA la
-- funcion tres arreglos. Quien pegara este archivo para completar lo que
-- faltaba se llevaba de regalo una funcion rota contra el esquema actual.
--
-- La leccion, que vale para los 17 archivos: un arreglo suelto no envejece
-- solo. Si otro posterior reescribe la misma funcion, el viejo deja de ser
-- «lo que falta» y pasa a ser «lo que no hay que pegar». Lo unico que
-- sobrevive aca es el ALTER, que es lo que `comprobar.sql` mira.
--
-- La version vigente de `tomar_turno()` esta en `arreglo-sin-asignar.sql`.
-- =====================================================================
